# **Основные алгоритмические конструкции**

**№1**

Дано натуральное трехзначное число N. Определить сумму и произведение его цифр.

In [ ]:
N = int(input())
summ = N % 1000 // 100 + N % 100 //10 +(N % 10) % 10
p = (N % 1000 // 100) * (N % 100 //10) * (N % 10 % 10)
print(summ, p, sep='\n')

111
3
1


**№2**

Одноклеточная амеба каждые 3 часа делится на 2 клетки. Определите, сколько амеб будет через N часов.

In [ ]:
print(2**(int(input())//3))

9
8


**№3**

Год високосный, если для номера этого года верно хотя бы одно из утверждений:

- делится на 4, но при этом не делится на 100;

- делится на 400.

Выведите количество дней в феврале года **y**.

In [ ]:
y = int(input())
if (y % 4 ==0 and y % 100 != 0) or y % 400 == 0:
    print(29)
else:
    print(28)

2013
28


**№4**

Для введенного натурального числа k напечатайте фразу:

Мне k лет

Учтите, что при некоторых значениях k слово "лет" надо заменить на слово "год" или "года".

In [ ]:
k = int(input())
if k % 10 == 1 and k != 11 and k != 111:
    print(f'Мне {k} год')
elif 2 <= k % 10 <= 4 and k not in [12,13,14,112,113,114]:
    print(f'Мне {k} года')
else:
    print(f'Мне {k} лет')

21
Мне 21 год


**№5**

Дана последовательность вещественных чисел Ai, в которой первый член неотрицателен, а также присутствует хотя бы один член, меньший нуля. Необходимо найти произведение всех элементов последовательности, предшествующих первому отрицательному члену. Пусть n — номер первого отрицательного члена последовательности. Тогда вы должны вычислить:
S=A1⋅A2⋅⋯⋅An−1

In [ ]:
x = float(input())
s = 1.0000
while x > 0:
    s *= x
    x = float(input())
print("{:f}".format(s))

1.000000
2.500000
-3.000000
2.500000


**№6**

Задана последовательность из N целых чисел. Необходимо найти порядковый номер числа с максимальным модулем. Если таких чисел несколько, вывести наибольший номер.


In [ ]:
N = int(input())
m = 0
for i in range(N):
    n = int(input())
    if abs(n) >= m:
        m = abs(n)
        k = i
print(k+1)

5
1
-2
-8
0
8
5


**№7**

В первый весенний день на березе распустилось A листьев, а в каждый последующий в 3 раза больше, чем в предыдущий. В какой день на дереве распустится не менее B листьев за один день? Через сколько дней на дереве будет как минимум 1000000 листьев?


In [ ]:
from math import log, ceil

A, B = map(int, input().split())
a1 = A
k = max(ceil(log(B/A,3)),0)+1

summ = a1
day = 1
while summ < 1000000:
    a1 *= 3
    summ += a1
    day += 1
print(k, day)

2 18
3 13


**№8**

Дано натуральное число N. Определить, является ли оно простым.



In [ ]:
N = int(input())
flag = 0
for i in range(2, int(N/2)+1,1):
    if N % i == 0:
        flag = 1
        break
print("No" if flag==1 else "Yes")

117
No


# **Строки и списки**

**№1**

Дано слово. Добавить к нему в начала и конце столько звёздочек, сколько букв в этом слове.

In [ ]:
s = input()
print('*'*len(s)+s+'*'*len(s))

word
****word****


**№2**

Дана строка, в которой имеются цифры. Найти их сумму.

In [ ]:
import re


s = input()
digits = re.findall("\d", s)
d = [int(x) for x in digits]
print(sum(d))


one - 1, two - 2, three - 3
6


**№3**

Дано слово s1. Получить слово s2, образованное четными буквами слова s1, записанными в обратном порядке.

In [ ]:
s1 = input()
print(s1[1::2][::-1])

Floccinaucinihilipilification
otcflplhncaicl


**№4**

В строке имеется несколько слов, разделенных одним или несколькими пробелами. Требуется убрать из строки лишние пробелы: два и более пробелов подряд, а также все пробелы в начале и в конце строки.


In [ ]:
s = input()
print(" ".join(s.split()))

   One    Two    Three
One Two Three


**№5**

Дан одномерный массив, состоящий из N целочисленных элементов. Увеличить все его элементы в k раз.

In [ ]:
N = int(input())
n = []
for i in range(N):
    n.append(int(input()))
k = int(input())
n = [k*x for x in n]
print(*n)

10
-1
2
-30
9
-90
3
2
1
10
23
20
-20 40 -600 180 -1800 60 40 20 200 460


**№6**

Дан массив целых чисел из N элементов. Необходимо заменить максимальный элемент на противоположный по знаку. Если элементов с максимальным значением несколько, замените только первый из них.

In [ ]:
N = int(input())
n = input().split()
n = [int(x) for x in n]
m = n[0]
k = 0
for i in range(N):
    if n[i] > m:
        m = n[i]
        k = i
n[k] = 0 - m
print(*n)

**№7**

Задан набор из N целых чисел. Найти сумму тех из них, которые заканчиваются на цифру K и при этом не кратны числу M. Исходно сумма полагается равной нулю.



In [ ]:
N, M, K = map(int, input().split())
n = input().split()
summ = 0
for i in range(N):
    if int(n[i][-1]) == K and int(n[i]) % M != 0:
        summ += int(n[i])
print(summ)

5 3 1
8 1 21 -51 -101
-100


**№8**

Дан признак геометрической фигуры на плоскости: k — круг, p — прямоугольник, t — треугольник. Вывести на экран периметр и площадь заданной фигуры.



In [ ]:
from math import pi, sqrt

param = input().split()
fig = param[0]
if fig == 'k':
    r = float(param[-1])
    P = 2*pi*r
    S = pi*r*r
elif fig == 't':
    a,b,c = float(param[1]), float(param[2]), float(param[3])
    P = a+b+c
    p  = P/2
    S = sqrt(p*(p-a)*(p-b)*(p-c))
else: 
    a,b = float(param[1]), float(param[2])
    P = 2*(a+b)
    S = a*b
print(round(P,4),round(S,4))

k 4.25
26.7035 56.745


# **Множества и словари**

**№1**

Дана строка. Определить, сколько различных букв в ней без учета регистра.

In [ ]:
print(len(set(input().lower())))

AasdgvSfa
6


**№2**

Дано натуральное четырехзначное число. Определить, повторяются ли какие-либо цифры в записи данного числа.


In [ ]:
print("NO" if len(set(input()))==4 else "YES")

123464
YES


**№3**

Даны две строки. Определить, можно ли из букв первой строки получить вторую строку. Повторяющиеся буквы второй строки могут в первой строке не повторяться.

In [ ]:
s1 = set(input())
s2 = set(input())
print(s2.issubset(s1))

redivider
ride
True


**№4**

Дан одномерный массив, элементы которого — целые числа. Удалите из него все элементы, в записи которых все цифры различны.

In [ ]:
N = int(input())
n = input().split()
m = []
for i in range(N):
    if len(n[i]) != len(set(n[i])):
        m.append(n[i])
print(*m)

4
9 8 7 525
525


**№5**

Дана буква английского алфавита. Если это I, V, X, L, C, D, M, то выдать десятичное значение данной римской цифры, иначе вывести число 0.

In [ ]:
d = {'I': 1,
     "V": 5, 
     "X": 10, 
     "L": 50, 
     "C": 100, 
     "D": 500, 
     "M": 1000
}

n = input()
if n in d.keys():
    print(d[n])
else:
    print(0)

I
1


**№6**

Даны числа m — порядковый номер масти, и k — номер достоинства карты. Масти нумеруются следующим образом: spades−1, clubs−2, diamonds−3, hearts−4. Достоинства определяются по следующему правилу: ace−14, king−13, queen−12, jack−11, ten−10, ..., six−6. Определить полное название соответствующей карты в формате "the достоинство of масть", например, "the ace of spades".


In [ ]:
d = {'spades': 1,
     "clubs": 2, 
     "diamonds": 3, 
     "hearts": 4,
     'ace': 14,
     "king": 13, 
     "queen": 12, 
     "jack": 11,
     "ten": 10,
     "nine": 9,
     "eight": 8,
     'seven': 7,
     'six': 6
}

m, k = map(int, input().split())
d_items = d.items()
for x in d_items:
    if m == x[1]:
        s1 = x[0]
    if k == x[1]:
        s2 = x[0]
print(f'the {s2} of {s1}')

4 13
the king of hearts


**№7**

Даны две строки. Определить, можно ли из букв первой строки получить вторую строку. Каждая буква второй строки должна входить в первое слово как минимум столько же раз, сколько раз она встречается во втором.


In [ ]:
s1 = input()
s2 = input()
set1 = set(s1)
set2 = set(s2)
res = "True"
if set2.issubset(set1):
    for x in s2:
        flag = (s1.count(x) >= s2.count(x))
        if not flag:
            res = "False"
            break
    print(res)
else:
    print("False")

redivider
divider
True


**№8**

Дана строка, состоящая из строчных латинских букв. Вывести в алфавитном порядке те буквы, которые встречаются только один раз.



In [ ]:
from string import ascii_lowercase as B 

s = input()
d = {x: 0 for x in B}
for x in s:
    d[x] += 1
p = ''
for k, v in d.items():
    if v == 1:
        p += k 
print(p)

honorificabilitudinitatibus
cdfhlrs


# **Функции**

**№1**

Дано натуральное число N и целые числа a1,a2,…,aN. Найти количество чисел ai (i=1,2,…,N), являющихся степенями пятерки. Решить задачу с помощью подпрограммы, которая позволяет распознавать степени пятерки

In [ ]:
def power_five(x):
    while x % 5 == 0:
        x = x//5
    if x == 1:
        return True
    else:
        return False

N = int(input())
a = [int(x) for x in input().split()]
print(len(([1 for x in a if power_five(x)])))

7
5 10 15 20 25 30 35
2


**№2**

Проверить гипотезу Гольдбаха: каждое четное число, большее двух, можно представить в виде суммы двух простых чисел. Решить задачу с помощью подпрограммы, которая позволяет распознавать простые числа.

In [ ]:
from math import sqrt

def prime(x):
    if 1 <= x <= 3:
        return True
    for i in range(2, int(sqrt(x))+1):
        if x % i == 0:
            return False
    return True

N = int(input())
for i in range(2, N):
    if prime(i) and prime(N-i):
        print(i, N-i)
        break

10
3 7


**№3**

Составьте процедуру, которая в данном одномерном массиве меняет местами минимальный и последний элемент. Если минимальных элементов в массиве несколько, выберите элемент с наименьшим индексом. Примените процедуру к каждому столбцу заданной прямоугольной матрицы.

In [ ]:
def func(m):
    k_min = 0
    min = m[0]
    for i in range(len(m)):
        if m[i] < min:
            min = m[i]
            k_min = i
    m[k_min], m[-1] = m[-1], m[k_min]
    return m

n, m = map(int, input().split())
a = [[int(x) for x in input().split()] for i in range(n)]
a = [list(i) for i in zip(*a)]
for i in range(m):
    a[i] = func(a[i])

a = [list(i) for i in zip(*a)]
print()
for i in range(n):
    print(' '.join(map(str, a[i])))

3 3
1 2 3
2 3 1
3 1 2

3 2 3
2 3 2
1 1 1


**№4**

Составить подпрограмму, которая заменяет в двумерном массиве четные элементы на нули.Проверить, будут ли равны два массива A и B после применения к ним этой подпрограммы.

In [ ]:
def matrix(n,m,A):
    for i in range(n):
        for j in range(m):
            if A[i][j] % 2 == 0:
                A[i][j] = 0
    return A

n, m = map(int, input().split())
A = [[int(x) for x in input().split()] for i in range(n)]
B = [[int(x) for x in input().split()] for i in range(n)]
 
print("YES" if matrix(n,m,A)==matrix(n,m,B) else "NO")

3 3
1 2 6
4 3 2
8 7 1
1 100 10
2 3 20
6 7 1
YES


**№5**

Составить подпрограмму транспонирования прямоугольной матрицы. Получить транспонированнную матрицу для матрицы размерности n на m.

In [ ]:
def transpose(n,m,A):
    if n == m:
        B = [[A[j][i] for j in range(m)] for i in range(n)]
    else:
        B = []
        for j in range(m):
            tmp=[]
            for i in range(n):
                tmp += [A[i][j]]
            B += [tmp]
    return B

n, m = map(int, input().split())
A = [[int(x) for x in input().split()] for i in range(n)]
print()
for row in transpose(n,m,A):
    print(*row)

2 3
1 2 6
4 3 2

1 4
2 3
6 2


**№6**

Составить подпрограмму перемножения матриц. С ее помощью вычислить n-ю степень квадратной матрицы A размера n на n.


In [ ]:
def multiplicate(A, B):
    n, m, k = len(A), len(A[0]), len(B[0])
    c = [[0]*k for i in range(n)]
    for i in range(n):
        for j in range(k):
            tmp = 0
            for r in range(m):
                tmp += A[i][r] * B[r][j]
            c[i][j] = tmp
    return c
            

n = int(input())
A = [[float(x) for x in input().split()] for i in range(n)]
if n == 2:
    B = multiplicate(A, A)
else:
    k = 2
    B = multiplicate(A,A)
    while k < n:
        B = multiplicate(A, B)
        k += 1
print()
for i in range(len(B)):
    B[i] = ["{:.3f}".format(x) for x in B[i]]
    print(' '.join(B[i]))

2
0.5 2
1 0

2.250 1.000
0.500 2.000


**№7**

Дано N строк. В каждой из них есть несколько пар круглых скобок. Написать подпрограмму, которая в данной строке удаляет круглые скобки вместе с текстом, который заключен между ними. Применить эту подпрограмму к каждой из данных строк.

In [ ]:
def deleteS(s):
    new_s = ''
    left = False
    right = False
    for x in s:
        if x == '(':
            left = True
        if x == ')':
            right = True
        if not left and not right:
            new_s += x
        if left and right:
            left = False
            right = False
    return new_s
    
n = int(input())
for _ in range(n):
    s = input()
    print(deleteS(s))

3
hello(world)
hello
abacaba
abacaba
aba(a)bba(aab)c
ababbac


**№8**

Напишите функцию для вычисления k-го члена последовательности Фибоначчи. Последовательность Фибоначчи образуется по закону: 

f_1=1,

f_2=1,

fi=f_{i−1}+f_{i−2} (i=3,4,...).

In [ ]:
def fib(n):
    if 0 <= n <= 1:
        return n
    else:
        res = [0, 1]
        for i in range(2,n+1):
            res.append(res[i-1]+res[i-2])
        return res[n]


n = int(input())
print(fib(n))

3
2


# **Файлы и сортировки**

**№1**

Дан текстовый файл. Найдите первые символы всех непустых строк.

In [ ]:
s = ''

with open("/content/input1.txt", "r") as file:
    for line in file:
        if line != '\n':
            s += line[0]
with open("/content/output1.txt", "w") as file:
    file.write(s)


**№2**

Дан текстовый файл. Требуется получить строку, образованную k - ми символами каждой строки.

In [ ]:
s = ''

with open("/content/input2.txt", "r") as file:
    lines = file.readlines()
lines = [line.rstrip() for line in lines]
k = int(lines[0])
for line in lines:
    if line != '\n':
        if len(line) >= k:
            s += line[k-1]
with open("/content/output2.txt", "w") as file:
    file.write(s)

**№3**

Дан текстовый файл. Найдите в нем самую длинную строку и ее длину. Если таких строк несколько, выведите первую.

In [ ]:
s = ''
lenS = 0

with open("/content/input3.txt", "r") as file:
    lines = file.readlines()
lines = [line.rstrip() for line in lines]
for x in lines:
    if x != '\n':
        if len(x) > lenS:
            lenS = len(x)
            s = x
with open("/content/output3.txt", "w") as file:
    file.write(s+'\n')
    file.write(str(lenS))

**№4**

Дан текстовый файл. Найдите номер самой длинной строки. Если таких строк несколько, выведите номер первой из них.

In [ ]:
numb = 0
lenS = 0

with open("/content/input4.txt", "r") as file:
    lines = file.readlines()
lines = [line.rstrip() for line in lines]
for i in range(len(lines)):
    if lines[i] != '\n':
        if len(lines[i]) > lenS:
            lenS = len(lines[i])
            numb = i+1  
with open("/content/output4.txt", "w") as file:
    file.write(str(numb))

**№5**

В текстовом файле содержатся записи о студентах. Для каждого студента известны его фамилия, имя, отчество, год рождения, оценки по пяти предметам. Необходимо отсортировать по возрастанию средней оценки (гарантируется, что средние оценки не повторяются).

In [ ]:
with open('/content/input5.txt', 'r') as file:
    N = int(file.readline())
    students = []
    for line in file:
        if line != '\n':
            line = line.split()
            F, I, O, Y, G = line[0], line[1], line[2], line[3], line[4:]
            Y = int(Y)
            G = [int(x) for x in G]
            students.append([F, I, O, Y, G])
students = sorted(students, key=lambda student: sum(student[4])/len(student[4]))
with open('/content/output5.txt', 'w') as file:
    perenos = '\n'
    for i in range(N):
        students[i][4] = ' '.join(map(str, students[i][4]))
        if i == N-1:
            perenos = ''
        file.write(' '.join(map(str, students[i]))+perenos)

**№6**

В текстовом файле содержатся записи о студентах. Для каждого студента известны его фамилия, имя, отчество, год рождения, оценки по пяти предметам. Необходимо отсортировать в алфавитном порядке по фамилии, а затем по убыванию года рождения.

In [ ]:
with open('/content/input6.txt', 'r') as file:
    N = int(file.readline())
    students = []
    for line in file:
        if line != '\n':
            line = line.split()
            F, I, O, Y, G = line[0], line[1], line[2], line[3], line[4:]
            Y = int(Y)
            G = [int(x) for x in G]
            students.append([F, I, O, Y, G])
students = sorted(students, key=lambda student: (student[0], -student[3]))
with open('/content/output6.txt', 'w') as file:
    perenos = '\n'
    for i in range(N):
        students[i][4] = ' '.join(map(str, students[i][4]))
        if i == N-1:
            perenos = ''
        file.write(' '.join(map(str, students[i]))+perenos)

**№7**

Дана квадратная матрица размерностью N×N содержащая целые числа. Необходимо отсортировать каждую строчку матрицы по убыванию элементов.

In [ ]:
with open('/content/input7.txt', 'r') as file:
    N = int(file.readline())
    matrix = []
    for line in file:
        if line != '\n':
            matrix.append(sorted([int(x) for x in line.split()], reverse=True))
with open('/content/output7.txt', 'w') as file:
    perenos = '\n'
    for i in range(N):
        if i == N-1:
            perenos = ''
        file.write(' '.join(map(str, matrix[i]))+perenos)

**№8**

Дана квадратная матрица размерностью N×N содержащая целые числа.Необходимо отсортировать каждый столбец матрицы по возрастанию элементов.

In [ ]:
with open('/content/input8.txt', 'r') as file:
    N = int(file.readline())
    matrix = []
    for line in file:
        if line:
            matrix.append([int(x) for x in line.split()])
matrix = [list(x) for x in zip(*matrix)]
matrix = [sorted(x) for x in matrix]
matrix = [list(x) for x in zip(*matrix)]
with open('/content/output8.txt', 'w') as file:
    perenos = '\n'
    for i in range(N):
        if i == N-1:
            perenos = ''
        file.write(' '.join(map(str, matrix[i]))+perenos)

**№9**

В текстовом файле содержатся записи о поставках товаров. Для каждой поставки указано наименование поставленного товара, фирма-производитель и количество. Необходимо вывести первые 10 поставок списка, полученного в результате сортировки исходного списка по наименованию товара (при совпадении наименований поставки сортируются по количеству товара в порядке невозрастания, при совпадении наименования и количества сохраняется исходный порядок) и исключения из списка поставок товаров фирмы, указанной в последней строке файла.

In [ ]:
with open('/content/input9.txt', 'r') as file:
    N = int(file.readline().rstrip())
    kol = 1
    inf = []
    for line in file:
        if line:
            if kol <= N:
                NAME, F, K = line.rstrip().split()
                K = int(K)
                inf.append([NAME, F, K])
                kol += 1
            else:
                iskl = line.rstrip()
inf = sorted(inf, key=lambda x: (x[0], -x[2]))
inf = [x for x in inf if x[1] != iskl]

with open('/content/output9.txt', 'w') as file:
    perenos = '\n'
    if len(inf) < 10:
        n = len(inf)
    else:
        n = 10
    for i in range(n):
        inf[i][2] = str(inf[i][2])
        if i == n-1:
            perenos = ''
        file.write(' '.join(map(str, inf[i]))+perenos)

**№10**

Дан набор из N карт — подмножество стандартной колоды из 52 карт. Необходимо сортировать карты каждой масти по рангу (2, 3, ..., 10, валет 11, дама 12, король 13, туз 14). Порядок, в котором следует расположить масти, также задан.

In [ ]:
with open('/content/input10.txt', 'r') as file:
    N = int(file.readline().rstrip())
    d = {'p': [], 'c': [], 'b': [], 'k': []}
    for i in range(N+1):
            if i < N:
                num, m = file.readline().rstrip().split() 
                num = int(num)
                d[m].append(num)
            else:
                por = file.readline().rstrip()
with open('/content/output10.txt', 'w') as file:
    kol = 0
    for x in por:
        s = ' '.join([f'{x}' for x in sorted(d[x])])
        if kol < 3:
            file.write(f'{x}: '+ s +'\n')
        else:
            file.write(f'{x}: '+ s )
        kol += 1

# **NumPy 1**

1. Сгенерировать матрицу размером 4 × 9, заполненную целыми числами.
2. Вывести на экран элемент с индексами [2, 6].
3. Вывести на экран каждый второй элемент третьей строки матрицы.
4. Вывести на экран элементы последнего столбца в обратном порядке.
5. Изменить форму матрицы с 4 × 9 на 6 × 6.
6. Возвести каждый элемент матрицы в заданную степень.
7. Найти минимум на главной диагонали.
8. Найти максимальный элемент в предпоследнем столбце.
9. Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.
10. Подсчитать произведение ненулевых элементов на побочной диагонали.

In [ ]:
import numpy as np
np.random.seed(0)

mas = np.random.randint(0, 10, (4,9)) # целые числа в промежутке от 0 до 10
print("1)", mas)

1) [[5 0 3 3 7 9 3 5 2]
 [4 7 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3 0]
 [3 5 0 2 3 8 1 3 3]]


In [ ]:
print("2)", mas[2,6])

2) 4


In [ ]:
print("3)", mas[2, 1::2]) 

3) [1 9 9 3]


In [ ]:
print("4)", mas[::-1,-1])

4) [3 0 7 2]


In [ ]:
mas = mas.reshape(6, 6)
print("5)", mas)

5) [[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]]


In [ ]:
s = int(input('Степень = '))
print("6)", mas**s)

Степень = 3
6) [[125   0  27  27 343 729]
 [ 27 125   8  64 343 216]
 [512 512   1 216 343 343]
 [512   1 125 729 512 729]
 [ 64  27   0  27 125   0]
 [  8  27 512   1  27  27]]


In [ ]:
print("7)", np.min(mas.diagonal()))

7) 1


In [ ]:
print("8)", np.max(mas[:, -2]))

8) 8


In [ ]:
print("9)", "YES" if np.array_equal(-np.sort(-np.ravel(mas)),np.ravel(mas)) else "NO") 

9) NO


In [ ]:
d = np.diag(np.fliplr(mas))
print("10)", np.prod(d[d != 0]))

10) 11340


# **Numpy 2**

In [ ]:
import numpy as np

**№1**

Дана целочисленная матрица A (квадратная таблица) размерностью N×N. Вывести максимальный элемент каждой строки матрицы.

In [ ]:
N = int(input())
A = np.array([[int(x) for x in input().split()] for i in range(N)])

print()
print(' '.join(map(str, np.array([np.max(A[i]) for i in range(N)]))))

3
1 2 3
4 5 6
7 8 9

3 6 9


**№2**

Дана целочисленная матрица A (квадратная таблица) размерностью N×N. Вывести максимальный элемент каждого столбца.

In [ ]:
N = int(input())
A = np.array([[int(x) for x in input().split()] for i in range(N)])

print()
print(' '.join(map(str, np.max(A, axis=0))))

3
1 2 3
4 5 6
7 8 9

7 8 9


**№3**

Дана целочисленная матрица A (квадратная таблица) размерностью N×N. Вывести элементы главной диагонали.

In [ ]:
N = int(input())
A = np.array([[int(x) for x in input().split()] for i in range(N)])

print()
print(' '.join(map(str, np.diagonal(A))))

3
1 0 0
0 1 0
0 0 1

1 1 1


**№4**

Дана целочисленная матрица A (квадратная таблица) размерностью N×N. Вывести элементы побочной диагонали

In [ ]:
N = int(input())
A = np.array([[int(x) for x in input().split()] for i in range(N)])

print()
print(' '.join(map(str, np.diag(np.fliplr(A))))) 

3
0 0 1
0 1 0
1 0 0

1 1 1


**№5**

Дана матрица A. Вычислите ее определитель.

In [ ]:
n = int(input())
A = np.array([[float(x) for x in input().split()] for i in range(n)])

print()
print(f'{np.linalg.det(A):.6f}')

2
1 1
1 -0.5

-1.500000


**№6**

Дана обратимая матрица A. Найдите обратную матрицу.

In [ ]:
n = int(input())
A = np.array([[float(x) for x in input().split()] for i in range(n)])
A_ = np.linalg.inv(A)

print()
for i in range(n):
    print(' '. join(map(str, [f'{x:.6f}' for x in A_[i]])))

2
1 1
1 -1.5

0.600000 0.400000
0.400000 -0.400000
